version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - archery_db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: archery
      MYSQL_DATABASE: archery
      MYSQL_USER: archery
      MYSQL_PASSWORD: archery

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: archery
      WORDPRESS_DB_PASSWORD: archery
      WORDPRESS_DB_NAME: archery
volumes:
  archery_db_data: {}
  wp-content: {}